/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IconVariant } from "./components/icon/icon.component";
import { IllustrationVariant } from "./components/illustration/illustration.component";
import { Placement } from "@popperjs/core";
export namespace Components {
    interface PButton {
        /**
          * The variant of the button
         */
        "variant": 'primary' | 'secondary';
    }
    interface PIcon {
        /**
          * Wether to flip the icon horizontally or vertically
         */
        "flip": 'horizontal' | 'vertical';
        /**
          * Wether to rotate the icon x degrees
         */
        "rotate": number;
        /**
          * The size of the icon, using tailwind sizes
         */
        "size": string;
        /**
          * The icon the be displayed
         */
        "variant": IconVariant;
    }
    interface PIllustration {
        /**
          * The icon the be displayed
         */
        "variant": IllustrationVariant;
    }
    interface PTooltip {
        /**
          * The content of the tooltip
         */
        "content": any;
        /**
          * Wether to force show the tooltip
         */
        "forceShow": boolean;
        /**
          * The content of the tooltip
         */
        "placement": Placement;
    }
}
declare global {
    interface HTMLPButtonElement extends Components.PButton, HTMLStencilElement {
    }
    var HTMLPButtonElement: {
        prototype: HTMLPButtonElement;
        new (): HTMLPButtonElement;
    };
    interface HTMLPIconElement extends Components.PIcon, HTMLStencilElement {
    }
    var HTMLPIconElement: {
        prototype: HTMLPIconElement;
        new (): HTMLPIconElement;
    };
    interface HTMLPIllustrationElement extends Components.PIllustration, HTMLStencilElement {
    }
    var HTMLPIllustrationElement: {
        prototype: HTMLPIllustrationElement;
        new (): HTMLPIllustrationElement;
    };
    interface HTMLPTooltipElement extends Components.PTooltip, HTMLStencilElement {
    }
    var HTMLPTooltipElement: {
        prototype: HTMLPTooltipElement;
        new (): HTMLPTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "p-button": HTMLPButtonElement;
        "p-icon": HTMLPIconElement;
        "p-illustration": HTMLPIllustrationElement;
        "p-tooltip": HTMLPTooltipElement;
    }
}
declare namespace LocalJSX {
    interface PButton {
        /**
          * The variant of the button
         */
        "variant"?: 'primary' | 'secondary';
    }
    interface PIcon {
        /**
          * Wether to flip the icon horizontally or vertically
         */
        "flip"?: 'horizontal' | 'vertical';
        /**
          * Wether to rotate the icon x degrees
         */
        "rotate"?: number;
        /**
          * The size of the icon, using tailwind sizes
         */
        "size"?: string;
        /**
          * The icon the be displayed
         */
        "variant"?: IconVariant;
    }
    interface PIllustration {
        /**
          * The icon the be displayed
         */
        "variant"?: IllustrationVariant;
    }
    interface PTooltip {
        /**
          * The content of the tooltip
         */
        "content"?: any;
        /**
          * Wether to force show the tooltip
         */
        "forceShow"?: boolean;
        /**
          * The content of the tooltip
         */
        "placement"?: Placement;
    }
    interface IntrinsicElements {
        "p-button": PButton;
        "p-icon": PIcon;
        "p-illustration": PIllustration;
        "p-tooltip": PTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "p-button": LocalJSX.PButton & JSXBase.HTMLAttributes<HTMLPButtonElement>;
            "p-icon": LocalJSX.PIcon & JSXBase.HTMLAttributes<HTMLPIconElement>;
            "p-illustration": LocalJSX.PIllustration & JSXBase.HTMLAttributes<HTMLPIllustrationElement>;
            "p-tooltip": LocalJSX.PTooltip & JSXBase.HTMLAttributes<HTMLPTooltipElement>;
        }
    }
}
