# .github/workflows/deploy.yml

# Workflow name
name: 'Deploy'

# Event for the workflow
on: push

# env:
# GIT_SSH_COMMAND: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no

# List of jobs
jobs:
    # lint:
    #     runs-on: ubuntu-latest
    #     if: |
    #         !contains(github.event.head_commit.message, 'no-release') && !contains(github.event.head_commit.message, 'Lerna publish')
    #     steps:
    #         - uses: actions/checkout@v2

    #         - name: Setup node
    #           uses: actions/setup-node@v2
    #           with:
    #               node-version: 14

    #         - uses: c-hive/gha-yarn-cache@v1

    #         - name: Install dependencies
    #           run: yarn

    # - name: Lint
    #   run: yarn lerna:lint

    build:
        runs-on: ubuntu-latest
        if: |
            !contains(github.event.head_commit.message, 'no-build') &&
            !contains(github.event.head_commit.message, 'Lerna publish')
        steps:
            - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

            - name: Setup node
              uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
              with:
                  always-auth: true
                  node-version: 14
                  registry-url: 'https://registry.npmjs.org'

            - uses: c-hive/gha-yarn-cache@1188bbd5a9af66e263de707cf9e97b7b7c942969 # tag=v1

            - uses: oleksiyrudenko/gha-git-credentials@1b0fce528e893ad7a9903c84e0055890d75e29e3 # tag=v2-latest
              with:
                  name: 'Github Actions'
                  email: 'actions@github.com'
                  token: '${{ secrets.GITHUB_TOKEN }}'

            - name: Version
              if: |
                  github.ref == 'refs/heads/main'
              run: yarn lerna:version:nopush

            - name: Install dependencies
              run: yarn

            - name: Build
              run: yarn lerna:build:prod

            - name: Push changes
              if: |
                  github.ref == 'refs/heads/main' &&
                  !contains(github.event.head_commit.message, 'chore')
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: ${{ github.ref }}
                  tags: true

            - name: Upload artifacts
              uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # tag=v2
              with:
                  name: build-artifact
                  path: |
                      lerna.json
                      CHANGELOG.md
                      packages/core/package.json
                      packages/core/CHANGELOG.md
                      packages/conventions/package.json
                      packages/conventions/CHANGELOG.md
                      packages/angular/package.json
                      packages/angular/CHANGELOG.md
                      packages/react/package.json
                      packages/react/CHANGELOG.md
                      packages/core/dist
                      packages/core/loader
                      packages/conventions/dist
                      packages/angular/dist
                      packages/react/dist

    release:
        needs: [build]
        runs-on: ubuntu-latest
        if: |
            github.ref == 'refs/heads/main' && 
            !contains(github.event.head_commit.message, 'no-release') &&
            !contains(github.event.head_commit.message, 'Lerna publish') &&
            !contains(github.event.head_commit.message , 'docs:') &&
            !contains(github.event.head_commit.message , 'docs(') &&
            !contains(github.event.head_commit.message, 'chore')
        steps:
            - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
              with:
                  fetch-depth: 0

            - name: Setup node
              uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
              with:
                  always-auth: true
                  node-version: 14
                  registry-url: 'https://registry.npmjs.org'

            - name: Download a single artifact
              uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # tag=v3
              with:
                  name: build-artifact

            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: yarn lerna:publish

    deploy-storybook:
        needs: [build]
        if: |
            github.ref == 'refs/heads/main' &&
            !contains(github.event.head_commit.message, 'no-build') &&
            !contains(github.event.head_commit.message, 'no-release') &&
            !contains(github.event.head_commit.message, 'Lerna publish')
        runs-on: ubuntu-latest
        # Job steps
        steps:
            - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
              with:
                  fetch-depth: 0

            - name: Download a single artifact
              uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # tag=v3
              with:
                  name: build-artifact

            - name: Install dependencies
              run: yarn

            - name: Build storybook
              run: yarn storybook:build

            - name: Deploy storybook
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: yarn storybook:deploy
