# .github/workflows/deploy.yml

# Workflow name
name: 'Deploy'

# Event for the workflow
on: push

# env:
# GIT_SSH_COMMAND: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no

# List of jobs
jobs:
    # lint:
    #     runs-on: ubuntu-latest
    #     if: |
    #         !contains(github.event.head_commit.message, 'no-release') && !contains(github.event.head_commit.message, 'Lerna publish')
    #     steps:
    #         - uses: actions/checkout@v2

    #         - name: Setup node
    #           uses: actions/setup-node@v2
    #           with:
    #               node-version: 14

    #         - uses: c-hive/gha-yarn-cache@v1

    #         - name: Install dependencies
    #           run: yarn

    # - name: Lint
    #   run: yarn lerna:lint

    build:
        runs-on: ubuntu-latest
        if: |
            !contains(github.event.head_commit.message, 'no-build') &&
            !contains(github.event.head_commit.message, 'Lerna publish')
        steps:
            - name: 'Checkout' # Download code from the repository
              uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
              with:
                  fetch-depth: 0 # Checkout all branches and tags

            - name: Setup node
              uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
              with:
                  always-auth: true
                  node-version: 18
                  registry-url: 'https://registry.npmjs.org'

            - uses: c-hive/gha-yarn-cache@d528cd63c28aed0a9f44b1cada95050d7aa95c2e # tag=v2

            - uses: oleksiyrudenko/gha-git-credentials@6132cfce45156e2c1562673f9be1a91a575ce879 # v2-latest
              with:
                  name: 'Github Actions'
                  email: 'actions@github.com'
                  token: '${{ secrets.GITHUB_TOKEN }}'

            - name: Version
              if: |
                  github.ref == 'refs/heads/main'
              run: yarn lerna:version:nopush

            - name: Install dependencies
              run: yarn

            - name: Build
              run: yarn lerna:build:prod

            - name: Push changes
              if: |
                  github.ref == 'refs/heads/main' &&
                  !contains(github.event.head_commit.message, 'chore')
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: ${{ github.ref }}
                  tags: true

            - name: Upload artifacts
              uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # tag=v3
              with:
                  name: build-artifact
                  path: |
                      lerna.json
                      CHANGELOG.md
                      packages/core/package.json
                      packages/core/CHANGELOG.md
                      packages/conventions/package.json
                      packages/conventions/CHANGELOG.md
                      packages/angular/package.json
                      packages/angular/CHANGELOG.md
                      packages/react/package.json
                      packages/react/CHANGELOG.md
                      packages/core/dist
                      packages/core/loader
                      packages/conventions/dist
                      packages/angular/dist
                      packages/react/dist

    release:
        needs: [build]
        runs-on: ubuntu-latest
        if: |
            github.ref == 'refs/heads/main' && 
            !contains(github.event.head_commit.message, 'no-release') &&
            !contains(github.event.head_commit.message, 'Lerna publish') &&
            !contains(github.event.head_commit.message , 'docs:') &&
            !contains(github.event.head_commit.message , 'docs(') &&
            !contains(github.event.head_commit.message, 'chore')
        steps:
            - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
              with:
                  fetch-depth: 0

            - name: Setup node
              uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
              with:
                  always-auth: true
                  node-version: 18
                  registry-url: 'https://registry.npmjs.org'

            - name: Download a single artifact
              uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7 # tag=v3
              with:
                  name: build-artifact

            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: yarn lerna:publish

    deploy-storybook:
        needs: [build]
        if: |
            github.ref == 'refs/heads/main' &&
            !contains(github.event.head_commit.message, 'no-build') &&
            !contains(github.event.head_commit.message, 'no-release') &&
            !contains(github.event.head_commit.message, 'Lerna publish')
        runs-on: ubuntu-latest
        # Job steps
        steps:
            - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
              with:
                  fetch-depth: 0

            - name: Download a single artifact
              uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7 # tag=v3
              with:
                  name: build-artifact

            - name: Install dependencies
              run: yarn

            - name: Build storybook
              run: yarn storybook:build

            - name: Deploy storybook
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: yarn storybook:deploy
